penguins: src/arguments.c File Reference
arguments.c File Reference
Functions
void init_arguments (Arguments *self)
void print_usage (const char *prog_name)
bool parse_arguments (Arguments *result, int argc, char *argv[])
Function Documentation
init_arguments()
void init_arguments (Arguments * self)
Definition at line 8 of file arguments.c.
Referenced by parse_arguments().
print_usage()
void print_usage (const char * prog_name)
Definition at line 20 of file arguments.c.
Referenced by main().
parse_arguments()
bool parse_arguments (Arguments * result, int argc, char * argv[])
Definition at line 36 of file arguments.c.
Referenced by main().