penguins: src/arguments.h File Reference
arguments.h File Reference
Detailed Description
The command-line argument parser.
Definition in file arguments.h.
Data Structures
struct Arguments
Enumerations
enum ActionArg {
ACTION_ARG_PRINT_HELP , ACTION_ARG_PRINT_VERSION , ACTION_ARG_INTERACTIVE , ACTION_ARG_PRINT_NAME ,
ACTION_ARG_PLACEMENT , ACTION_ARG_MOVEMENT , ACTION_ARG_GENERATE , ACTION_ARG_VIEW
}
enum GenerateArg { GENERATE_ARG_NONE , GENERATE_ARG_ISLAND , GENERATE_ARG_RANDOM }
Functions
void init_arguments (Arguments *self)
void print_usage (const char *prog_name)
bool parse_arguments (Arguments *result, int argc, char *argv[])
Enumeration Type Documentation
ActionArg
enum ActionArg
Enumerator
ACTION_ARG_PRINT_HELP
ACTION_ARG_PRINT_VERSION
ACTION_ARG_INTERACTIVE
ACTION_ARG_PRINT_NAME
ACTION_ARG_PLACEMENT
ACTION_ARG_MOVEMENT
ACTION_ARG_GENERATE
ACTION_ARG_VIEW
Definition at line 13 of file arguments.h.
GenerateArg
enum GenerateArg
Enumerator
GENERATE_ARG_NONE
GENERATE_ARG_ISLAND
GENERATE_ARG_RANDOM
Definition at line 24 of file arguments.h.
Function Documentation
init_arguments()
void init_arguments (Arguments * self)
Definition at line 8 of file arguments.c.
Referenced by parse_arguments().
print_usage()
void print_usage (const char * prog_name)
Definition at line 20 of file arguments.c.
Referenced by main().
parse_arguments()
bool parse_arguments (Arguments * result, int argc, char * argv[])
Definition at line 36 of file arguments.c.
Referenced by main().