penguins: src/autonomous.c File Reference
autonomous.c File Reference
Macros
#define MAX_PLAYERS 9
#define MIN_PLAYER_ID 1
#define MAX_PLAYER_ID 9
Functions
int run_autonomous_mode (const Arguments *args)
static size_t read_line (FILE *file, char **buf, size_t *line_len)
bool load_game_state (Game *game, FILE *file, int penguins_arg, const char *my_player_name)
bool save_game_state (const Game *game, FILE *file)
Variables
const char * MY_AUTONOMOUS_PLAYER_NAME = "102D"
Macro Definition Documentation
MAX_PLAYERS
#define MAX_PLAYERS 9
Definition at line 20 of file autonomous.c.
MIN_PLAYER_ID
#define MIN_PLAYER_ID 1
Definition at line 21 of file autonomous.c.
MAX_PLAYER_ID
#define MAX_PLAYER_ID 9
Definition at line 22 of file autonomous.c.
Function Documentation
run_autonomous_mode()
int run_autonomous_mode (const Arguments * args)
Definition at line 24 of file autonomous.c.
Referenced by main().
read_line()
static size_t read_line (FILE * file, char ** buf, size_t * line_len) static
Definition at line 122 of file autonomous.c.
Referenced by load_game_state().
load_game_state()
bool load_game_state (Game * game, FILE * file, int penguins_arg, const char * my_player_name)
Definition at line 142 of file autonomous.c.
Referenced by run_autonomous_mode().
save_game_state()
bool save_game_state (const Game * game, FILE * file)
Definition at line 292 of file autonomous.c.
Referenced by run_autonomous_mode().
Variable Documentation
MY_AUTONOMOUS_PLAYER_NAME
const char* MY_AUTONOMOUS_PLAYER_NAME = "102D"
Definition at line 17 of file autonomous.c.
Referenced by run_autonomous_mode().