penguins: src/interactive.h File Reference
interactive.h File Reference
Detailed Description
The interactive-mode text user interface.
Definition in file interactive.h.
Functions
int run_interactive_mode (void)
void print_board (const Game *game)
void print_player_stats (const Game *game)
void print_game_state (const Game *game)
void interactive_placement (Game *game)
void handle_placement_input (Game *game, Coords *selected)
void interactive_movement (Game *game)
void handle_movement_input (Game *game, Coords *penguin, Coords *target)
Function Documentation
run_interactive_mode()
int run_interactive_mode (void)
Definition at line 133 of file interactive.c.
Referenced by main().
print_board()
void print_board (const Game * game)
Definition at line 53 of file interactive.c.
Referenced by print_game_state().
print_player_stats()
void print_player_stats (const Game * game)
Definition at line 102 of file interactive.c.
Referenced by print_game_state().
print_game_state()
void print_game_state (const Game * game)
Definition at line 122 of file interactive.c.
Referenced by run_autonomous_mode(), and update_game_state_display().
interactive_placement()
void interactive_placement (Game * game)
Definition at line 220 of file interactive.c.
Referenced by run_interactive_mode().
handle_placement_input()
void handle_placement_input (Game * game, Coords * selected)
Definition at line 234 of file interactive.c.
Referenced by interactive_placement().
interactive_movement()
void interactive_movement (Game * game)
Definition at line 267 of file interactive.c.
Referenced by run_interactive_mode().
handle_movement_input()
void handle_movement_input (Game * game, Coords * penguin, Coords * target)
Definition at line 282 of file interactive.c.
Referenced by interactive_movement().