name: Docs
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docs:
    name: Update documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt update
          sudo apt install doxygen graphviz libgtk-3-dev
      - run: cmake -B build -DBUILD_WXWIDGETS_FROM_SOURCE=YES -DGENERATE_WXWIDGETS_DOC_TAGS=YES
      - run: cmake --build build -j"$(nproc)" --target doxygen
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html/
          force_orphan: true
